# Generated by Django 3.2.19 on 2023-06-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad_model',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
