# Generated by Django 3.2.19 on 2023-06-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_alter_ad_model_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad_model',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
